# Generated by Django 4.2.20 on 2025-04-23 03:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postimage",
            old_name="user",
            new_name="post",
        ),
    ]
